In [9]:
import numpy as np

#x = np.ones(12).reshape(4,3)
#y = np.zeros(12).reshape(4,3)
#print(x)
#print(y)

x = np.identity(4)
#print(x)
#x[:,2]



array([0., 0., 1., 0.])

In [17]:
k = [7, 8, 9, 10, 11, 12]
x = np.array(k).reshape(2, 3)

print(x)

#x.transpose()

np.fliplr(x)
np.flipud(x)

[[ 7  8  9]
 [10 11 12]]


array([[10, 11, 12],
       [ 7,  8,  9]])

In [19]:
y = np.arange(6).reshape(2, 3)
print(y)

[[0 1 2]
 [3 4 5]]


In [20]:
yy = np.arange(1, 10, 2)
print(yy)

[1 3 5 7 9]


In [22]:
a1 = np.zeros(9).reshape(3, 3)
a1[1, 1] = 5
print(a1)

[[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]


In [25]:
a = np.array([10, 3, 25, 2, 67, 12])
b = np.array([43, 3, 12, 50, 7, 21])
print(a>b)

[False False  True False  True False]


In [33]:
print("Sum: ", a.sum())
print("Product: ", a.prod())
print(a.cumsum())
print(x.sum(axis=0))
print(x.sum(axis=1))

Sum:  119
Product:  1206000
[ 10  13  38  40 107 119]
[17 19 21]
[24 33]


In [35]:
c = np.hstack((a, b))
print(c)

[10  3 25  2 67 12 43  3 12 50  7 21]


In [37]:
c = np.vstack((a,b))
print(c)

[[10  3 25  2 67 12]
 [43  3 12 50  7 21]]


In [40]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[53  6 37 52 74 33]
[-33   0  13 -48  60  -9]
[430   9 300 100 469 252]
[0.23255814 1.         2.08333333 0.04       9.57142857 0.57142857]


In [43]:
print(c*a)

[[ 100    9  625    4 4489  144]
 [ 430    9  300  100  469  252]]


In [45]:
m1 = np.random.random(6).reshape(3, 2)
print(m1)

[[0.9234259  0.03371305]
 [0.65006449 0.03572933]
 [0.21246738 0.2850675 ]]
